openapi: 3.0.3
info:
  title: Person
  description: API to read and update the Person in this system
  version: 1.0.0
servers:
  - url: 'http://localhost:8088/api'
    description: 'Localhost for testing on your own device'
paths:
  '/person':
    get:
      description: "Get the list of all people in the system"
      responses:
        "200":
          description: "Complete list of people."
          content:
            application/json:
              schema:
                type: "array"
                items:
  '/person/{id}':
    get:
      summary: "Find person with the id"
      description: "Find the person with the requested id"
      operationId: "getPersonById"
      responses:
        "200":
          description: "Person response"
          content:
            'application/json': {}
        "404":
          description: "Person not found"
          content:
            'application/json': {}
